config/routes.rb
Library::Application.routes.draw do

  root :to => 'pages#home'
  match 'about' => 'pages#about', :as => :about

  devise_for :users

  resources :documents

  match 'courses/batch_update' => 'courses#batch_update', :as => :course_batch_update
  match 'courses/batch_update/confirm' => 'courses#confirm_batch_update', :as => :course_batch_update_confirm
  match 'courses/search' => 'courses#search', :as => :course_search
  resources :courses

end

app/models/document.rb
class Document < ActiveRecord::Base
  attr_accessible :title, :course_id, :year, :semester, :category, :file
  belongs_to :course
  has_attached_file :file,
    :url => '/documents/:id/:attachment/:filename',
    :storage => if ENV['PAPERCLIP_STORAGE'] then ENV['PAPERCLIP_STORAGE'] else :filesystem end,
    :bucket => ENV['AWS_S3_BUCKET'],
    :s3_credentials => {
      :access_key_id => ENV['AWS_ACCESS_KEY_ID'],
      :secret_access_key => ENV['AWS_SECRET_ACCESS_KEY']
    }

  def self.semesters
    ['Fall','Winter','Spring','Summer']
  end

  def self.categories
    ['Final','Test','Quiz','Notes','Other']
  end
end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController
  before_filter :authenticate_user!, :except => [:index, :show]
  before_filter :except => [:index, :show] do
    redirect_to new_user_session_path unless current_user && current_user.admin?
  end

  # GET /documents
  # GET /documents.json
  def index
    @documents = Document.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @documents }
    end
  end

  # GET /documents/1
  # GET /documents/1.json
  def show
    @document = Document.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @document }
    end
  end

  # GET /documents/new
  # GET /documents/new.json
  def new
    @document = Document.new
    if params[:course] then
      course = Course.find(params[:course])
      @document.course = course if course
    end

    respond_to do |format|
      format.html
      format.json { render json: @document }
    end
  end

  # GET /documents/1/edit
  def edit
    @document = Document.find(params[:id])
  end

  # POST /documents
  # POST /documents.json
  def create
    @document = Document.new(params[:document])

    respond_to do |format|
      if @document.save
        format.html { redirect_to @document, notice: 'Document was successfully created.' }
        format.json { render json: @document, status: :created, location: @document }
      else
        format.html { render :new }
        format.json { render json: @document.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /documents/1
  # PUT /documents/1.json
  def update
    @document = Document.find(params[:id])

    respond_to do |format|
      if @document.update_attributes(params[:document])
        format.html { redirect_to @document, notice: 'Document was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render :edit }
        format.json { render json: @document.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /documents/1
  # DELETE /documents/1.json
  def destroy
    @document = Document.find(params[:id])
    @document.destroy

    respond_to do |format|
      format.html { redirect_to documents_url }
      format.json { head :ok }
    end
  end
end

app/views/documents/_form.html.haml
= form_for document, :html => {:multipart => true} do |f|
  -if document.errors.any?
    #error_explanation
      %h2= "#{pluralize(document.errors.count, "error")} prohibited this document from being saved:"
      %ul
        - document.errors.full_messages.each do |msg|
          %li= msg

  -if document.course
    %h2 Adding to #{document.course.code}
    = f.hidden_field :course_id, :value => document.course.id
  .field
    = f.label :category
    = f.select(:category, options_for_select(Document.categories))
  .field
    = f.label :year
    = f.text_field :year
  .field
    = f.label :semester
    = f.select(:semester, options_for_select(Document.semesters))
  .field
    = f.label :title
    = f.text_field :title
  .field
    = f.label :file
    = f.file_field :file
  .actions
    = f.submit 'Save'

app/views/documents/edit.html.haml
%h1 Editing document

= render 'form', :document => @document

= link_to 'Show', @document
\|
= link_to 'Back', documents_path

app/views/documents/index.html.haml
%h1 Listing documents

%table
  %tr
    %th Title
    %th Last Updated
    -if user_signed_in? && current_user.admin?
      %th

  - @documents.each do |document|
    %tr
      %td= link_to document.title, document
      %td= "#{time_ago_in_words(document.updated_at)} ago"
      -if user_signed_in? && current_user.admin?
        %td
          .btn-group
            =link_to 'Show', document, :class => 'btn'
            =link_to 'Edit', edit_document_path(document), :class => 'btn'
            =link_to 'Destroy', document, :confirm => 'Are you sure?', :method => :delete, :class => ['btn', 'btn-danger']

%br

app/views/documents/new.html.haml
%h1 New document

= render 'form', :document => @document

= link_to 'Back', documents_path

app/views/documents/show.html.haml
%p#notice= notice

%h1 #{@document.course.code} - #{@document.title}

%table
  %tr
    %td
      %b Course:
    %td
      =link_to @document.course.code, course_path(@document.course)
  %tr
    %td
      %b Year:
    %td
      =@document.year
  %tr
    %td
      %b Semester:
    %td
      =@document.semester

%div
  -if @document.file.exists?
    =link_to @document.file.url, :class => 'btn' do
      %i.icon-cloud-download
      Download
  -else
    Hardcopy Available in ENG111

-if user_signed_in? && current_user.admin?
  = link_to 'Edit', edit_document_path(@document)
  \|
= link_to "Back to #{@document.course.code}", course_path(@document.course)