config/routes.rb
Library::Application.routes.draw do

  root :to => 'pages#home'
  match 'about' => 'pages#about', :as => :about

  devise_for :users

  resources :documents

  match 'courses/batch_update' => 'courses#batch_update', :as => :course_batch_update
  match 'courses/batch_update/confirm' => 'courses#confirm_batch_update', :as => :course_batch_update_confirm
  match 'courses/search' => 'courses#search', :as => :course_search
  resources :courses

end

app/controllers/courses_controller.rb
require 'iconv'
class CoursesController < ApplicationController
  before_filter :authenticate_user!, :except => [:index, :show, :search]
  before_filter :except => [:index, :show, :search] do
    redirect_to new_user_session_path unless current_user && current_user.admin?
  end

  # GET /courses
  # GET /courses.json
  def index
    @courses = Course.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @courses }
    end
  end

  # GET /courses/1
  # GET /courses/1.json
  def show
    @course = Course.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @course }
    end
  end

  # GET /courses/new
  # GET /courses/new.json
  def new
    @course = Course.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @course }
    end
  end

  # GET /courses/1/edit
  def edit
    @course = Course.find(params[:id])
  end

  # POST /courses
  # POST /courses.json
  def create
    @course = Course.new(params[:course])

    respond_to do |format|
      if @course.save
        format.html { redirect_to @course, notice: 'Course was successfully created.' }
        format.json { render json: @course, status: :created, location: @course }
      else
        format.html { render :new }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /courses/1
  # PUT /courses/1.json
  def update
    @course = Course.find(params[:id])

    respond_to do |format|
      if @course.update_attributes(params[:course])
        format.html { redirect_to @course, notice: 'Course was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render :edit }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /courses/1
  # DELETE /courses/1.json
  def destroy
    @course = Course.find(params[:id])
    @course.destroy

    respond_to do |format|
      format.html { redirect_to courses_url }
      format.json { head :ok }
    end
  end

  # GET /courses/batch_update
  def batch_update
  end

  def confirm_batch_update
    @calendar_url = params[:calendar_url]
    ryerson_page = Mechanize.new.get(@calendar_url)
    ryerson_page = Iconv.new('UTF-8//IGNORE', 'UTF-8').iconv(ryerson_page.content)
    ryerson_page = Nokogiri.parse(ryerson_page)
    @courses = Course.create_from_ryerson_calendar(ryerson_page)
    redirect_to courses_url
  end


  # GET /courses/search/:code
  def search
    param = params[:query]
    course = Course.find_by_code(param)
    if course.nil? then
      redirect_to courses_url
    else
      redirect_to course
    end
  end
end

app/helpers/courses_helper.rb
module CoursesHelper
  def sort_by_year(documents)
    documents.sort do |a,b|
      if a.year.nil? then
        1
      elsif b.year.nil? then
        -1
      else
        b.year <=> a.year
      end
    end
  end
end

app/views/courses/_form.html.haml
= form_for course do |f|
  -if course.errors.any?
    #error_explanation
      %h2= "#{pluralize(course.errors.count, "error")} prohibited this course from being saved:"
      %ul
        - course.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :code
    = f.text_field :code
  .field
    = f.label :description
    = f.text_area :description
  .actions
    = f.submit 'Save'

app/views/courses/batch_update.html.haml
= form_tag course_batch_update_confirm_path, :method => 'get' do
  .field
    = label_tag :calendar_url, "Ryerson Calendar URL"
    = text_field_tag :calendar_url
  .actions
    = submit_tag 'Batch Update'

app/views/courses/confirm_batch_update.html.haml
%h1 Batch Updating from #{@calendar_url}
%h2 Found #{@courses.size} courses
= form_for "course[]" do |f|
  - @courses.each do |course|
    = f.fields_for course do |fields|
      .field
        = fields.label :code
        = fields.text_field :code
      .field
        = fields.label :name
        = fields.text_field :name
      .field
        = fields.label :description
        = fields.text_area :description

  = submit_tag 'Batch Update'

app/views/courses/edit.html.haml
%h1 Editing course

= render 'form', :course => @course

= link_to 'Show', @course
\|
= link_to 'Back', courses_path

app/views/courses/index.html.haml
-if user_signed_in? && current_user.admin?
  =link_to new_course_path, :class => 'btn' do
    %i.icon-plus-sign
    New Course
%table.table.table-striped
  %tr
    %th Name
    %th Code
    %th # of Documents
    %th Last Updated
    -if user_signed_in? && current_user.admin?
      %th

  - @courses.sort{|a,b| a.code <=> b.code}.each do |course|
    %tr
      %td= link_to course.code, course
      %td= course.name
      %td= course.documents.count
      %td= "#{time_ago_in_words(course.last_update_time)} ago"
      -if user_signed_in? && current_user.admin?
        %td
          .btn-group
            =link_to 'Show', course, :class => 'btn'
            =link_to 'Edit', edit_course_path(course), :class => 'btn'
            =link_to 'Destroy', course, :confirm => 'Are you sure?', :method => :delete, :class => ['btn', 'btn-danger']

app/views/courses/new.html.haml
%h1 New course

= render 'form', :course => @course

= link_to 'Back', courses_path

app/views/courses/show.html.haml
%p#notice= notice

.hero-unit
  %h1
    = @course.code
  %h2
    = @course.name
  %p
    = @course.description


- unless @course.documents.empty?
  %h2 Documents
  %table.table-striped.document-list
    %tr
      %th Title
      %th Type
      %th Semester
      %th Year
      %th Last Updated
      %th
      - sort_by_year(@course.documents).each do |doc|
        %tr
          %td
            =link_to doc.title, document_path(doc)
          %td
            =doc.category
          %td
            =doc.semester
          %td
            =doc.year
          %td
            ="#{time_ago_in_words(doc.updated_at)} ago"
          %td
            - if doc.file.exists?
              =link_to doc.file.url, :class => 'btn' do
                %i.icon-cloud-download
                Download
            - else
              Available in ENG111
-if user_signed_in? && current_user.admin?
  = link_to new_document_path({:course => @course}), :class => 'btn' do
    %i.icon-plus-sign
    Add Document

- unless @course.prerequisites.empty?
  %h2
    Prerequisites
  %table.table-striped
    %tr
      %th Code
      %th Title
    - @course.prerequisites.each do |prereq|
      %tr
        %td= link_to prereq.code, course_path(prereq)
        %td= prereq.name

%hr

-if user_signed_in? && current_user.admin?
  = link_to 'Edit', edit_course_path(@course)
  \|
= link_to 'Back', courses_path