config/routes.rb
Library::Application.routes.draw do

  root :to => 'pages#home'
  match 'about' => 'pages#about', :as => :about

  devise_for :users

  resources :documents

  match 'courses/batch_update' => 'courses#batch_update', :as => :course_batch_update
  match 'courses/batch_update/confirm' => 'courses#confirm_batch_update', :as => :course_batch_update_confirm
  match 'courses/search' => 'courses#search', :as => :course_search
  resources :courses

end

app/views/layouts/application.html.haml
!!!html5
%html
  %head
    %title CSCU Exam Bank
    =stylesheet_link_tag 'application'
    =javascript_include_tag 'application'
    =csrf_meta_tags
    -if !ENV['GOOGLE_ANALYTICS_ID'].blank?
      :javascript
        var _gaq = _gaq || [];
        _gaq.push(['_setAccount', '#{ENV['GOOGLE_ANALYTICS_ID']}']);
        _gaq.push(['_trackPageview']);

        (function() {
          var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
          ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
          var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
        })();
  %body
    .navbar
      .navbar-inner
        =link_to "CSCU Exam Bank", root_path, :class => 'brand'
        %ul.nav
          %li
            =link_to "Courses", courses_path
        %form{:action => course_search_path, :class => 'navbar-search'}
          %input{:type => 'search', :name => 'query', :class => 'search-query', :placeholder => 'Search by Course Code'}
          %input{:type => 'submit', :value => 'Search', :style => 'display:none;'}
        %ul.nav.pull-right
          %li
            =link_to "About", about_path
          -if user_signed_in?
            %li
              =link_to destroy_user_session_path, :method=>'delete' do
                %i.icon-signout
                Logout
          -else
            %li
              =link_to new_user_session_path do
                %i.icon-signin
                Login
    .container
      =yield